### ISSUE TITLE
FloradoBrasil Consulta e mapeamento (53.3h)

### ISSUE THREAD

**Issue by eriyuri1213** [nakaosensei/Jisatsu#15]

**Comment by nakaosensei** [comment]
Realização de consultas no site floradobrasil para extrair informações de interesse das 1096 espécies passadas pelas clientes.

Lembrete:
No site floradobrasil, existem os nomes aceitos e os nomes corretos pra cada planta, os nomes aceitos são os sinonimos e o nome correto é o de maior impacto.

Para cada espécie, deve-se coletar:
Autor
Lista de sinônimos na forma
{nome,autor}

**Comment by eriyuri1213** [comment]
B=30h, W=90h, A=50h, PERT=53.3h

**Comment by nakaosensei** [comment]
Inicío de trabalho - 09/11/2018 - 15:50
